### ISSUE TITLE
Reset research

### ISSUE THREAD

**Issue by bdraco** [Bluetooth-Devices/usb-devices#3]
First try power reset if that fails and returns false go to the usb reset

1. Find the device by `readlink` on `/sys/class/bluetooth/hci0/device`
```# ls -l /sys/class/bluetooth/hci0/device
lrwxrwxrwx    1 root     root             0 Nov 26 22:03 /sys/class/bluetooth/hci0/device -> ../../../1-1.2.2:1.0
```

2. split `1-1.2.2:1.0` to get `1-1.2.2`
3. `/sys/bus/usb/devices/1-1.2.4.2/{manufacturer,product,idProduct,idVendor}` gives us data about the adapter (we can use this for `bluetooth-devices`)
4. `/sys/bus/usb/devices/1-1.2.4.2/devnum` gives us the device id which is 7
5. split `1-1.2.2` to get `1`
6.  Take the 1 and format it as 001, Take the devnum and format it as 007 Do the reset on `/dev/bus/usb/001/007`
```
open(/dev/bus/usb/001/007, 'rw')
ioctl(USBDEVFS_RESET, 0)
```
If >0 its successful

openat(AT_FDCWD, "/sys/bus/usb/devices/1-1.2.4.2/manufacturer", O_RDONLY|O_LARGEFILE) = 7
read(7, "Realtek\n", 128)               = 8
close(7)                                = 0
openat(AT_FDCWD, "/sys/bus/usb/devices/1-1.2.4.2/product", O_RDONLY|O_LARGEFILE) = 7
read(7, "Bluetooth Radio\n", 128)       = 16
close(7)                                = 0

/sys/bus/usb/devices/1-1.2.4.2
bash-5.1# cat idProduct 
a725
bash-5.1# cat idVendor 
0bda

bash-5.1# cd /sys/class/bluetooth/
bash-5.1# ls
hci1  hci2  hci3

/sys/bus/usb/devices/1-1.2.4.2/devnum

bash-5.1# cat /sys/bus/usb/devices/1-1.2.4.2/devnum 
7

/sys/class/bluetooth/hci0
bash-5.1# ls -la
total 0
drwxr-xr-x    4 root     root             0 Nov 26 11:48 .
drwxr-xr-x    3 root     root             0 Nov 26 11:48 ..
lrwxrwxrwx    1 root     root             0 Nov 26 12:03 device -> ../../../1-1.2.2:1.0

Split the :1.0 to lookup in /sys/bus/usb/devices

/dev/bus/usb/001/007

bash-5.1# cd /sys/class/bluetooth/
bash-5.1# ls -la
total 0
drwxr-xr-x    2 root     root             0 Nov 23 12:24 .
drwxr-xr-x   72 root     root             0 Nov 23 12:24 ..
lrwxrwxrwx    1 root     root             0 Nov 26 11:55 hci0 -> ../../devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2/1-1.2.2/1-1.2.2:1.0/bluetooth/hci0
lrwxrwxrwx    1 root     root             0 Nov 26 11:55 hci1 -> ../../devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2/1-1.2.4/1-1.2.4.3/1-1.2.4.3:1.0/bluetooth/hci1
lrwxrwxrwx    1 root     root             0 Nov 26 11:55 hci2 -> ../../devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2/1-1.2.4/1-1.2.4.2/1-1.2.4.2:1.0/bluetooth/hci2
lrwxrwxrwx    1 root     root             0 Nov 26 11:55 hci3 -> ../../devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2/1-1.2.1/1-1.2.1:1.0/bluetooth/hci3

**Comment by dbuezas** [comment]
Sharing in case it may serve as yet another option:

I've been using this to revive the adapter by resetting the usb device:
```bash
#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

VENDOR="0bda" # this is specific to the device 
PRODUCT="8771"

for DIR in $(find /sys/bus/usb/devices/ -maxdepth 1 -type l); do
  if [[ -f $DIR/idVendor && -f $DIR/idProduct &&
        $(cat $DIR/idVendor) == $VENDOR && $(cat $DIR/idProduct) == $PRODUCT ]]; then
    echo disabling $DIR
    echo 0 > $DIR/authorized
    echo sleeping
    sleep 0.5
    echo enabling $DIR
    echo 1 > $DIR/authorized
    echo done
  fi
done
```

I think I took it from here https://askubuntu.com/a/910350

**Comment by bdraco** [comment]
Thanks.  Authorized didn't seem to fix some of the Realtek adapters but the usbdevfs reset I just implemented does.

**Comment by bdraco** [comment]
Closing since this has been implemented and integrated into Bluetooth auto recovery
